---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ws-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ws-service
    spec:
      containers:
      - name: ws-service
        image: mcsdevopsentarch.azurecr.io/ws-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: myseckey