---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: ws-service
#   labels:
#     app: ws-service
#     deployment: blue
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: ws-service
#       deployment: blue
#   template:
#     metadata:
#       labels:
#         app: ws-service
#         deployment: blue
#     spec:
#       containers:
#       - name: ws-service
#         image: mcsdevopsentarch.azurecr.io/ws-service:latest
#         resources:
#           requests:
#             cpu: 500m
#             memory: 128Mi
#           limits:
#             cpu: 1000m
#             memory: 256Mi
#         ports:
#         - containerPort: 4000
#           name: http
#           protocol: TCP
#       imagePullSecrets:
#       - name: myseckey

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ws-service
  labels:
    app: ws-service
spec:
  # modify pod replicas according to your case 
  replicas: 1
  selector:
    matchLabels:
      app: ws-service            
  template:
    metadata:
      labels:
        app: ws-service
        version: "2"
    spec:
      containers:
      - name: ws-service
        image: mcsdevopsentarch.azurecr.io/ws-service:latest
        resources:
          requests:  #request a Pod with  a minimum of 0.5 of a core and 128 MB of memory
            cpu: "500m"
            memory: "128Mi"
          limits:    #add a limit of 1.0 CPU and 256 MB of memory
            cpu: "1000m"   
            memory: "256Mi" 
        ports:
        - containerPort: 4000
          name: http
          protocol: TCP  