
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-service
  labels:
    app: fe-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe-service
  template:
    metadata:
      labels:
        app: fe-service
    spec:
      containers:
      - name: fe-service
        image: mcsdevopsentarch.azurecr.io/fe-service:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: myseckey
