---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fe-service-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fe-service
    spec:
      containers:
      - name: fe-service
        image: mcsdevopsentarch.azurecr.io/bp-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 22137
      imagePullSecrets:
      - name: myseckey