---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-service
  labels:
    run: fe-service
spec:
  replicas: 1
  selector:
    matchLabels:
      run: fe-service
      version: 0.0.1
  template:
    metadata:
      labels:
        run: fe-service
        version: 0.0.1
    spec:
      containers:
      - name: fe-service
        image: mcsdevopsentarch.azurecr.io/bp-service:0.0.1
        resources:
          requests:
            cpu: 500m
            memory: 128Mi
          limits:
            cpu: 1000m
            memory: 256Mi
        ports:
        - containerPort: 4000
          name: http
          protocol: TCP
      imagePullSecrets:
      - name: myseckey