---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws-service
  labels:
    app: ws-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ws-service
  template:
    metadata:
      labels:
        app: ws-service
    spec:
      containers:
      - name: ws-service
        image: mcsdevopsentarch.azurecr.io/ws-service:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: myseckey

# ---
# apiVersion: v1
# kind: Deployment
# metadata:
#   name: ws-service
# spec:
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         app: ws-service
#     spec:
#       containers:
#       - name: backendservice
#         image: mcsdevopsentarch.azurecr.io/ws-service:latest
#         resources:
#           requests:
#             cpu: "500m"
#             memory: "128Mi"
#           limits:
#             cpu: "1000m"
#             memory: "256Mi"
#         volumeMounts:
#         - mountPath: "/mnt/backendservice"
#           name: azurelogs
#         imagePullPolicy: Always
#         ports:
#         - containerPort: 4000
#         #env:
#         # - name: AZURE_STORAGE_ACCOUNT_NAME
#         #   value: ""
#         # - name: AZURE_STORAGE_ACCOUNT_KEY
#         #   value: ""
#         # - name: AZURE_STORAGE_CONTAINER_NAME
#         #   value: "backendservice"
#       imagePullSecrets:
#       - name: myseckey
