# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.
FROM anapsix/alpine-java:8u151b12_jdk

copy target/BPRestWS-1.0-SNAPSHOT-swarm.jar .

CMD ["java", "-Djava.net.preferIPv4Stack=true", "-jar", "BPRestWS-1.0-SNAPSHOT-swarm.jar"]