FROM kanolanacr.azurecr.io/bprestws-hollow:latest

EXPOSE 8080

copy JAVA_APP/target/BPRestWS-1.0-SNAPSHOT.war .
CMD ["java", "-Djava.net.preferIPv4Stack=true", "-jar", "BPRestWS-1.0-SNAPSHOT-hollow-swarm.jar", "BPRestWS-1.0-SNAPSHOT.war"]
