---
- name: Security AutoAdding IP
  hosts: localhost
  vars:
    webHttpPort:
      - 80
    webHttpsPort:
      - 443
    sshPort:
      - 22
    jenkinsPort:
      - 8080
    mongoDbPort:
      - 1433
  vars_files:
    - ../inventories/{{ env }}/{{ env }}_vars.yaml
    - ../inventories/{{ env }}/{{ env }}_vault.yaml
    - ./vars/ips.yaml
  remote_user: root
  tasks:

  - name: Az set subscription
    local_action: shell /usr/bin/az account set -s "{{ azureSubId }}"
    become: no
    run_once: true
    tags:
      - always

  - name: Update rules on existing security group
    azure_rm_securitygroup:
      resource_group: "devops"
      name: "devops"
      rules:
          # - name: DenySSH
          #   protocol: Tcp
          #   destination_port_range: 22-23
          #   access: Deny
          #   priority: 100
          #   direction: Inbound
          - name: AllowSSHFromHome
            protocol: Tcp
            # source_address_prefix: '174.109.158.0/24'
            # destination_port_range: 22-23
            # access: Allow
            priority: 102
            # direction: Inbound

  # Add HTTP access for Jenkins
  # - name: Update Jenkins Security group access
  #   azure_rm_securitygroup:
  #     resource_group: "{{ devops.rg.name }}"
  #     name: "{{ devops.nsg.name }}"
  #     subscription_id: "{{ azureSubId }}"
  #     client_id: "{{ az_client_id }}"
  #     tenant: "{{ az_tenant_id}}"
  #     secret: "{{ az_secret }}"
  #     rules:
  #       - name: IP_HTTP_Whitelist_Auto
  #         protocol: Tcp
  #         source_address_prefix: "{{ item.ips }}"
  #         destination_port_range: "{{ jenkinsPort }}"
  #         access: Allow
  #         priority: 130
  #         direction: Inbound
  #   with_items:
  #   - { ips: "{{ allowedIPs }}" }

  # - name: Update SSH Access
  #   azure_rm_securitygroup:
  #     resource_group: "devops"
  #     name: "devops"
  #     subscription_id: "{{ azureSubId }}"
  #     client_id: "{{ az_client_id }}"
  #     tenant: "{{ az_tenant_id}}"
  #     secret: "{{ az_secret }}"
  #     rules:
  #         - name: denyssh
  #           protocol: Tcp
  #           source_address_prefix: 132
  #           destination_port_range: "22"
  #           access: Allow
  #           priority: 110
  #           direction: Inbound
    # with_items:
    # - { ips: "{{ sshDevOpsAccess }}" }