- hosts: localhost
  gather_facts: no
  connection: local
  become: no
  vars:
    kubectl: "/usr/local/bin/kubectl"
    inventoryDir: "{{ playbook_dir }}/inventories/{{ env }}"
    ansible_connection: local
    env: "{{ env }}"
    ansible_ssh_port: "{{ ssh_port | default(22)}}"
  vars_files:
    - "{{ inventoryDir }}/{{ env }}_vault.yaml"
  roles:
    - role: login
    - role: manage_azure