- hosts: localhost
  gather_facts: no
  connection: local
  #become: true
  vars:
    kubectl: "/usr/local/bin/kubectl"
    inventoryDir: "{{ playbook_dir }}/inventories/{{ env }}"
    #ansibleServerIP: "{{ ansibleIP | default('40.118.43.201') }}"
    ansible_connection: local
    env: "{{ env }}"
    ansible_ssh_port: "{{ ssh_port | default(22)}}"
  vars_files:
    - "{{ inventoryDir }}/{{ env }}_vault.yaml"
  roles:
    - role: login
    - role: manage_azure