---
- name: Create a managed Azure Container Services (AKS) instance
  azure_rm_aks:
    name: "{{ aks.name }}"
    location: "{{ location }}"
    resource_group: "{{ aks.rg }}"
    dns_prefix: aksdns
    kubernetes_version: "{{ aks.version }}"
    linux_profile:
      admin_username: "{{ linux_profile_ssh_username }}"
      ssh_key: "{{ linux_profile_ssh_key }}" 
    service_principal:
      client_id: "{{ aks.client.id }}"
      client_secret: "{{ aks.client.secret }} "
    agent_pool_profiles:
      - name: mscdevops-agent-pool
        count: 1
        vm_size: Standard_B2s
    tags: "{{ mscdevops.tags }}"
  tags:
    - createAks

- name: Remove a managed Azure Container Services (AKS) instance
  azure_rm_aks:
    name: "{{ aks.name }}"
    resource_group: "{{ aks.rg }}"
    state: absent
  tags:
    - deleteAks
