---
- name: Include variables
  include_vars: "../../../inventories/{{ env }}/{{ env }}_vars.yaml"
  tags:
    - always

- name: Include variables from nsgautomation
  include_vars: "../../../nsgautomation/vars/ips.yaml"
  tags:
    - createNsg

- name: Login to azure by az login
  shell: "az login --service-principal -u {{ az_client_id }} -p {{ az_secret }} -t {{ az_tenant_id}}"
  tags:
    - always

- name: Az set subscription
  local_action: shell /usr/bin/az account set -s "{{ azureSubId }}"
  become: no
  run_once: true
  tags:
    - always
  
- name: Include task for creating resource groups
  include_tasks: "{{ item }}"
  with_items:
    - "resource_group.yaml"
  tags: 
    - createRg

- name: Include tasks for creating vnets
  include_tasks: "{{ item }}"
  with_items:
    - "vnet.yaml"
  tags:
    - createVnet
    - deleteVnet

- name: Include tasks for creating nsg
  include_tasks: "{{ item }}"
  with_items:
    - "nsg.yaml"
  tags:
    - createNsg
    - deleteNsg

- name: Include tasks for creating subnets
  include_tasks: "{{ item }}"
  with_items:
    - "subnet.yaml"
  tags:
    - createSubnet
    - deleteSubnet

- name: Include tasks for creating aks
  include_tasks: "{{ item }}"
  with_items:
    - "aks.yaml"
  tags:
    - createAks
    - deleteAks

- name: Include tasks for aks postdeplyment tasks
  include_tasks: "{{ item }}"
  with_items:
    - "postdeploy.yaml"
  tags:
    - createAks

- name: Include tasks for deleting resource groups
  include_tasks: "{{ item }}"
  with_items:
    - "deleterg.yaml"
  tags:
    - deleteRg