---
- name: Include variables
  include_vars: "../../../inventories/{{ env }}/{{ env }}_vars.yaml"
  tags:
    - always

- name: Login to azure by az login
  shell: "az login --service-principal -u {{ az_client_id }} -p {{ az_secret }} -t {{ az_tenant_id}}"
  tags:
    - always

- name: Include task for creating AKS
  include_tasks: "{{ item }}"
  with_items:
    - "resource_group.yaml"
    - "vnet.yaml"
    - "subnet.yaml"
    - "aks.yaml"
  tags:
    - createrg
    - createaks