---
- name: Include variables
  include_vars: "../../../inventories/{{ env }}/{{ env }}_vars.yaml"
  tags:
    - always

- name: Include variables from nsgautomation
  include_vars: "../../../nsgautomation/vars/ips.yaml"
  tags:
    - createNsg

- name: Include task to login to azure as a service principal
  include_tasks: "{{ item }}"
  with_items:
    - "../../login/tasks/login.yaml"
  tags: 
    - always

- name: Include task for creating resource groups
  include_tasks: "{{ item }}"
  with_items:
    - "resource_group.yaml"
  tags: 
    - createRg

- name: Include tasks for creating network
  include_tasks: "{{ item }}"
  with_items:
    - "vnet.yaml"
    - "lb.yaml"
    - "pip.yaml"
  tags:
    - createVnet
    - deleteVnet



- name: Include tasks for creating nsg
  include_tasks: "{{ item }}"
  with_items:
    - "nsg.yaml"
  tags:
    - createNsg
    - deleteNsg

- name: Include tasks for creating subnets
  include_tasks: "{{ item }}"
  with_items:
    - "subnet.yaml"
  tags:
    - createSubnet
    - deleteSubnet

- name: Include tasks for creating aks
  include_tasks: "{{ item }}"
  with_items:
    - "aks.yaml"
  tags:
    - createAks
    - deleteAks

- name: Include tasks for aks management
  include_tasks: "{{ item }}"
  with_items:
    - "manage-aks.yaml"
  tags:
    - manageAks

- name: Include tasks for aks postdeplyment tasks
  include_tasks: "{{ item }}"
  with_items:
    - "postdeploy.yaml"
  tags:
    - createAks

- name: Include tasks for deleting resource groups
  include_tasks: "{{ item }}"
  with_items:
    - "deleterg.yaml"
  tags:
    - deleteRg
