---
- name: Include variables
  include_vars: "../../../inventories/{{ env }}/{{ env }}_vars.yaml"
  tags:
    - always

- name: Login to azure by az login
  shell: "az login --service-principal -u {{ az_client_id }} -p {{ az_secret }} -t {{ az_tenant_id}}"
  tags:
    - always

- name: Manage databases
  include_tasks: "{{ item }}"
  with_items:
    - "database.yaml"
  tags:
    - createdb
    - removedb

- name: Include task for creating AKS
  include_tasks: "{{ item }}"
  with_items:
    - "aks.yaml"
  tags:
    - createaks

- name: Include tasks for managing NSG roles
  include_tasks: "{{ item }}"
  with_items:
  - "nsg.yaml"
  tags:
    - awxaccess
    - manageonensg
    - updateaksnsgrules
    - removeaksnsg
    - managesqlfirewall