---
- name: Create NSG resource group
  azure_rm_securitygroup:
    resource_group: "{{ nsg.rg}}"
    name: "{{ nsg.name }}"
    location: "{{ location }}"
    purge_rules: "yes"
    tags: "{{ mscdevops.tags }}"
    rules:
      - name: DenySSH
        description: "deny ssh"
        protocol: Tcp
        destination_port_range: 22
        access: Deny
        priority: 100
        direction: Inbound
      - name: AllowSSH
        protocol: Tcp
        source_address_prefix: "{{ item.ips }}"
        destination_port_range: 22
        access: Allow
        priority: 101
        direction: Inbound
      - name: 'AllowMultiplePorts'
        protocol: Tcp
        source_address_prefix: "{{ item.ips }}"
        destination_port_range:
          - 80
          - 443
        access: Allow
        priority: 102
  with_items:
  - { ips: "{{ allowedIPs }}" }
  tags:
    - createNsg
  
- name: Delete security group
  azure_rm_securitygroup:
      resource_group: "{{ nsg.rg}}"
      name: "{{ nsg.name }}"
      state: absent
  tags:
    - deleteNsg
  
  