---
- name: Create NSG resource group
  azure_rm_securitygroup:
      resource_group: "{{ nsg.rg}}"
      name: "{{ nsg.name }}"
      location: "{{ location }}"
      purge_rules: "yes"
      client_id: "{{ az_client_id }}"     
      rules:
        - name: DenySSH
          description: "deny ssh"
          protocol: Tcp
          destination_port_range: "22"
          access: Deny
          priority: "100"
          direction: Inbound
      secret: "{{ az_secret }}"    
      subscription_id: "{{ azureSubId }}"
      tenant: "{{ az_tenant_id}}"

          # - name: 'AllowSSH'
          #   protocol: Tcp
          #   source_address_prefix:
          #     - '77.252.197.165/24'
          #     - '168.208.6.11/24'
          #   destination_port_range: 22
          #   access: Allow
          #   priority: 101
          #   direction: Inbound
          # - name: 'AllowMultiplePorts'
          #   protocol: Tcp
          #   source_address_prefix:
          #     - '77.252.197.165/24'
          #     - '168.208.6.11/24'
          #   destination_port_range:
          #     - 80
          #     - 443
          #   access: Allow
          #   priority: 102
  