---
- name: Add Ips
  vars:
    webHttpPort:
      - 80
    webHttpsPort:
      - 443
    sshPort:
      - 22
    jenkinsPort:
      - 8080
    mongoDbPort:
      - 1433
  vars_files:
    - ../../../inventories/{{ env }}/{{ env }}_vars.yaml
    - ./vars/ips.yaml
  remote_yser: root
  tasks:
  - name: Az set subscription
    local_action: shell /usr/bin/az account set -s "{{ azureSubId }}"
    become: no
    run_once: true
    tags:
      - always
# # add HTTP access for Jenkins
#   - name: Update Jenkins Security group access
#     azure_rm_securitygroup:
#       resource_group: "{{ devops.rg.name }}"
#       name: "{{ devops.nsg.name }}"
#       rules:
#         - name: IP_HTTP_Whitelist_Auto
#           protocol: Tcp
#           source_address_prefix: "{{ item.ips }}"
#           destination_port_range:
#             - "{{ jenkinsPort }}"
#           access: Allow
#           priority: 130
#           direction: Inbound
#     with_items:
#     - { ips: "{{ allowedIPs }}" }
#   - name: Update SSH Access
#     azure_rm_securitygroup:
#       resource_group: "{{ devops.rg.name }}"
#       name: "{{ devops.nsg.name }}"
#       rules:
#       - name: denyssh
#         protocol: Tcp
#         source_address_prefix: "{{ item.ips }}"
#         destination_port_range:
#           - "{{ sshPort }}"
#         access: Allow
#         priority: 110
#         direction: Inbound
#     with_items:
#     - { ips: "{{ sshDevOpsAccess }}" }