- name: Create VM public ip address
  azure_rm_publicipaddress:
    name: "{{ vm.pip.name }}"
    resource_group: "{{ resourceGroupName }}"
    allocation_method: Static
    domain_name_label: "{{ pipShortNodeHostName }}"
    subscription_id: "{{ azureSubId }}"
    client_id: "{{ az_client_id }}"
    tenant: "{{ az_tenant_id}}"
    secret: "{{ az_secret }}"
  register: vm_pip_facts
  tags:
    - createvm
    - createrg
    - doormanrg

- name: Create APPGW public ip address
  azure_rm_publicipaddress:
    name: "{{ appgw.pip.name }}"
    resource_group: "{{ resourceGroupName }}"
    allocation_method: "{{ appgw.pip.allocation }}"
    domain_name_label: "{{ appgw.domain.label }}"
    subscription_id: "{{ azureSubId }}"
    client_id: "{{ az_client_id }}"
    tenant: "{{ az_tenant_id}}"
    secret: "{{ az_secret }}"
  when: ( tertiary is not defined or tertiary == "no" ) and ( networking.subnet is defined )
  tags:
    - createappgw
    - createrg

# Delete public IPs

- name: Delete vm public ip address
  azure_rm_publicipaddress:
    name: "{{ vm.pip.name }}"
    resource_group: "{{ resourceGroupName }}"
    state: absent
    subscription_id: "{{ azureSubId }}"
    client_id: "{{ az_client_id }}"
    tenant: "{{ az_tenant_id}}"
    secret: "{{ az_secret }}"
  tags:
    - deletevm
    - deleterg

- name: Delete appgw public ip address
  azure_rm_publicipaddress:
    name: "{{ appgw.pip.name }}"
    resource_group: "{{ resourceGroupName }}"
    state: absent
    subscription_id: "{{ azureSubId }}"
    client_id: "{{ az_client_id }}"
    tenant: "{{ az_tenant_id}}"
    secret: "{{ az_secret }}"
  when: tertiary is not defined or tertiary == "no"
  tags:
    - deleteappgw
    - deleterg