---
- name: Create NSG resource group
  azure_rm_resourcegroup:
    name: "{{ nsg.rg }}"
    location: "{{ location }}"
    tags: "{{ mscdevops.rg.tags }}"
    subscription_id: "{{ azureSubId }}"
    client_id: "{{ az_client_id }}"
    tenant: "{{ az_tenant_id}}"
    secret: "{{ az_secret }}"
    force: True
  run_once: "{{ run_mode_once | default(false) }}"
  when: ( nsg is defined and nsg.rg is defined )
  tags: createRg

- name: Create VNET resource group
  azure_rm_resourcegroup:
    name: "{{ vnet.rg }}"
    location: "{{ location }}"
    tags: "{{ mscdevops.rg.tags }}"
    subscription_id: "{{ azureSubId }}"
    client_id: "{{ az_client_id }}"
    tenant: "{{ az_tenant_id}}"
    secret: "{{ az_secret }}"
    force: True
  run_once: "{{ run_mode_once | default(false) }}"
  when: ( vnet.rg is defined )
  tags: createRg

- name: Create AKS resource group
  azure_rm_resourcegroup:
    name: "{{ aks.rg }}"
    location: "{{ location }}"
    tags: "{{ mscdevops.rg.tags }}"
    subscription_id: "{{ azureSubId }}"
    client_id: "{{ az_client_id }}"
    tenant: "{{ az_tenant_id}}"
    secret: "{{ az_secret }}"
    force: True
  run_once: "{{ run_mode_once | default(false) }}"
  tags: createRg