---
- name: Create a subnet for AKS
  azure_rm_subnet:
    name: "{{ aks.subnet.name }}"
    resource_group: "{{ vnet.rg }}"
    virtual_network_name: "{{ vnet.name }}"
    address_prefix_cidr: "{{ networking.subnet.aks }}"
    security_group:
      name: "{{ nsg.name }}"
      resource_group: "{{ nsg.rg }}"
    subscription_id: "{{ azureSubId }}"
    client_id: "{{ az_client_id }}"
    tenant: "{{ az_tenant_id}}"
    secret: "{{ az_secret }}"
  when: ( networking.subnet is defined )
  tags:
    - createSubnet

# Could ne used explicitly if not deleting whole rg
- name: Delete AKS subnet
  azure_rm_subnet:
    name: "{{ aks.subnet.name }}"
    resource_group: "{{ vnet.rg }}"
    virtual_network_name: "{{ vnet.name }}"
    state: absent
    subscription_id: "{{ azureSubId }}"
    client_id: "{{ az_client_id }}"
    tenant: "{{ az_tenant_id}}"
    secret: "{{ az_secret }}"
  when: ( networking.subnet is defined )
  tags:
    - deleteSubnet