- name: Create a subnet for corda VM
  azure_rm_subnet:
    name: "{{ vm.subnet.name }}"
    resource_group: "{{ vnet.rg }}"
    virtual_network_name: "{{ vnet.name }}"
    address_prefix_cidr: "{{ networking.subnet.corda }}"
    security_group:
      name: "{{ vm.nsg.name }}"
      resource_group: "{{ vm.nsg.rg }}"
    subscription_id: "{{ azureSubId }}"
    client_id: "{{ az_client_id }}"
    tenant: "{{ az_tenant_id}}"
    secret: "{{ az_secret }}"
  when: networking.subnet is defined
  tags:
    - createvm
    - createrg
    - doormanrg

- name: Add service endpoint to subnet
  shell: "az network vnet subnet update --subscription {{ azureSubId }} --resource-group {{ vnet.rg }} --name {{ vm.subnet.name }} --service-endpoints Microsoft.Sql --vnet-name {{ vnet.name }}"
  tags:
    - postdeployment

- name: Ceate a subnet for API Management
  azure_rm_subnet:
    name: "{{ apim.subnet.name }}"
    resource_group: "{{ vnet.rg }}"
    virtual_network_name: "{{ vnet.name }}"
    address_prefix_cidr: "{{ networking.subnet.apim }}"
    security_group:
      name: "{{ apim.nsg.name }}"
      resource_group: "{{ apim.nsg.rg }}"
    subscription_id: "{{ azureSubId }}"
    client_id: "{{ az_client_id }}"
    tenant: "{{ az_tenant_id}}"
    secret: "{{ az_secret }}"
  when: ( tertiary is not defined or tertiary == "no" ) and ( networking.subnet is defined ) and ( networking.subnet.apim is defined )
  tags:
    - createapim
    - createrg

- name: Create a subnet for APP Gateway
  azure_rm_subnet:
    name: "{{ appgw.subnet.name }}"
    resource_group: "{{ vnet.rg }}"
    virtual_network_name: "{{ vnet.name }}"
    address_prefix_cidr: "{{ networking.subnet.appgw }}"
    security_group:
      name: "{{ appgw.nsg.name }}"
      resource_group: "{{ appgw.nsg.rg }}"
    subscription_id: "{{ azureSubId }}"
    client_id: "{{ az_client_id }}"
    tenant: "{{ az_tenant_id}}"
    secret: "{{ az_secret }}"
  when: ( tertiary is not defined or tertiary == "no" ) and ( networking.subnet is defined )
  tags:
    - createappgw
    - createrg

- name: Create a subnet for AKS
  azure_rm_subnet:
    name: "{{ aks.subnet.name }}"
    resource_group: "{{ vnet.rg }}"
    virtual_network_name: "{{ vnet.name }}"
    address_prefix_cidr: "{{ networking.subnet.aks }}"
    security_group:
      name: "{{ aks.nsg.name }}"
      resource_group: "{{ aks.nsg.rg }}"
    subscription_id: "{{ azureSubId }}"
    client_id: "{{ az_client_id }}"
    tenant: "{{ az_tenant_id}}"
    secret: "{{ az_secret }}"
  when: ( tertiary is not defined or tertiary == "no" ) and ( networking.subnet is defined )
  tags:
    - createaks
    - createrg

- name: Add service endpoint to AKS subnet
  shell: "az network vnet subnet update --subscription {{ azureSubId }} --resource-group {{ vnet.rg }} --name {{ aks.subnet.name }} --service-endpoints Microsoft.Sql --vnet-name {{ vnet.name }}"
  when: ( tertiary is not defined or tertiary == "no" ) and ( networking.subnet is defined )
  tags:
    - postdeployment

# Delete subnets for VM, APPGW, AKS

- name: Delete VM subnet
  azure_rm_subnet:
    name: "{{ vm.subnet.name }}"
    resource_group: "{{ vnet.rg }}"
    virtual_network_name: "{{ vnet.name }}"
    state: absent
    subscription_id: "{{ azureSubId }}"
    client_id: "{{ az_client_id }}"
    tenant: "{{ az_tenant_id}}"
    secret: "{{ az_secret }}"
  when: ( tertiary is not defined or tertiary == "no" ) and ( networking.subnet is defined )
  tags:
    - deletevm
    - deleterg

- name: Delete APPGW subnet
  azure_rm_subnet:
    name: "{{ appgw.subnet.name }}"
    resource_group: "{{ vnet.rg }}"
    virtual_network_name: "{{ vnet.name }}"
    state: absent
    subscription_id: "{{ azureSubId }}"
    client_id: "{{ az_client_id }}"
    tenant: "{{ az_tenant_id}}"
    secret: "{{ az_secret }}"
  when: ( tertiary is not defined or tertiary == "no" ) and ( networking.subnet is defined )
  tags:
    - deleteappgw
    - deleterg

- name: Delete AKS subnet
  azure_rm_subnet:
    name: "{{ aks.subnet.name }}"
    resource_group: "{{ vnet.rg }}"
    virtual_network_name: "{{ vnet.name }}"
    state: absent
    subscription_id: "{{ azureSubId }}"
    client_id: "{{ az_client_id }}"
    tenant: "{{ az_tenant_id}}"
    secret: "{{ az_secret }}"
  when: ( tertiary is not defined or tertiary == "no" ) and ( networking.subnet is defined )
  tags:
    - deleteaks
    - deleterg

- name: Delete APIM subnet
  azure_rm_subnet:
    name: "{{ apim.subnet.name }}"
    resource_group: "{{ vnet.rg }}"
    virtual_network_name: "{{ vnet.name }}"
    state: absent
    subscription_id: "{{ azureSubId }}"
    client_id: "{{ az_client_id }}"
    tenant: "{{ az_tenant_id}}"
    secret: "{{ az_secret }}"
  when: ( tertiary is not defined or tertiary == "no" ) and ( networking.subnet is defined )
  tags:
    - deleteaks
    - deleterg