---
- name: Create a virtual network
  azure_rm_virtualnetwork:
    name: "{{ vnet.name }}"
    resource_group: "{{ vnet.rg }}"
    address_prefixes_cidr: "{{ networking.vnet_cidr }}"
    dns_servers: "{{ networking.dns }}"
    subscription_id: "{{ azureSubId }}"
    client_id: "{{ az_client_id }}"
    tenant: "{{ az_tenant_id}}"
    secret: "{{ az_secret }}"
  when: networking.vnet_cidr is defined
  tags:
    - createVnet

#Could ne used explicitly if not deleting whole rg
- name: Delete a virtual network
  azure_rm_virtualnetwork:
    name: "{{ vnet.name }}"
    resource_group: "{{ vnet.rg }}"
    state: absent
    subscription_id: "{{ azureSubId }}"
    client_id: "{{ az_client_id }}"
    tenant: "{{ az_tenant_id}}"
    secret: "{{ az_secret }}"
  when: networking.vnet_cidr is defined
  tags:
    - deleteVnet